const UF=(id)=>{const u=id?users().find(x=>x.id===id):{};modal(id?'Edit user':'Add user',`<label>Full name<input name=name value="${esc(u.name)}" required></label><label>Email<input type=email name=email value="${esc(u.email)}" required></label><label>Phone<input name=phone value="${esc(u.phone)}" pattern="[0-9+ ()\\-]{7,}" title="Valid phone number" required></label><label>Role<select name=role>${['patient','doctor','admin'].map(r=>`<option ${u.role===r?'selected':''}>${r}</option>`).join('')}</select></label><label>Status<select name=status><option ${u.status!=='Inactive'?'selected':''}>Active</option><option ${u.status==='Inactive'?'selected':''}>Inactive</option></select></label>${id?'':'<label>Password<input type=password name=password required minlength=4></label>'}`,f=>{const v=fd(f);delete v.password;const l=users();if(id)Object.assign(l.find(x=>x.id===id),v);else{const x={id:'u_'+uid(),reg:today(),...v};if(v.role==='doctor'){x.spec='General Medicine';x.exp=1;x.rating=4.5}l.push(x);notify('admin','New user added: '+v.name)}db.set('users',l);toast(id?'User updated successfully.':'User added successfully.');redraw()})};
function drawU(){const q=($('#uq').value||'').toLowerCase(),r=$('#ur').value;const l=users().filter(u=>(!q||(u.name+u.email+u.id).toLowerCase().includes(q))&&(!r||u.role===r));
$('#ut').innerHTML=l.length?`<div class=tw><table><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Role</th><th>Phone</th><th>Registered</th><th>Status</th><th>Actions</th></tr></thead><tbody>${l.map(u=>`<tr><td>${u.id}</td><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.role}</td><td>${esc(u.phone)}</td><td>${u.reg}</td><td>${badge(u.status)}</td><td>${ab('View/Edit',`UF('${u.id}')`)}${ab(u.status==='Active'?'Deactivate':'Activate',`togU('${u.id}')`)}${ab('Delete',`confirmBox('Delete this user permanently?',()=>delU('${u.id}'))`)}</td></tr>`).join('')}</tbody></table></div>`:empty('👥','No users found','Adjust search or add a user.')}
function togU(id){const l=users(),u=l.find(x=>x.id===id);u.status=u.status==='Active'?'Inactive':'Active';db.set('users',l);toast('User '+u.status.toLowerCase()+'.','info');redraw()}
function delU(id){db.set('users',users().filter(u=>u.id!==id));toast('User deleted.','warning');redraw()}
const SF=[['clinic','Clinic name'],['email','Email','email'],['phone','Phone'],['address','Address'],['tz','Timezone'],['duration','Appointment duration (min)','number'],['window','Booking window (days)','number'],['maxDaily','Max daily appointments','number'],['cancelHrs','Cancellation policy (hours before)','number'],['timeout','Session timeout (min)','number'],['pwPolicy','Password policy'],['n_email','Email notifications','checkbox'],['n_rem','Appointment reminders','checkbox'],['n_sys','System alerts','checkbox'],['n_pat','Patient notifications','checkbox'],['loginNote','Login notifications','checkbox']];
function saveSet(e){e.preventDefault();const s=settings(),f=e.target;SF.forEach(([k,,t])=>{s[k]=t==='checkbox'?(f[k].checked?1:0):t==='number'?+f[k].value:f[k].value});db.set('settings',s);toast('Settings updated successfully.')}
const cnt=(l,k)=>l.reduce((o,x)=>(o[x[k]]=(o[x[k]]||0)+1,o),{});
shell('admin',[['dashboard','Dashboard','▦'],['users','Users','👥'],['appointments','Appointments','📅'],['analytics','Analytics','📈'],['settings','System Settings','⚙'],['notifications','Notifications','🔔']],{
dashboard(){const a=appts(),u=users(),n=getSession().name;return `<h2>Welcome back, ${esc(n)}</h2><div class=grid>${stat('Total Users',u.length,'👥','▲ 8% vs last month')}${stat('Doctors',u.filter(x=>x.role==='doctor').length,'🩺','▲ 2 new')}${stat('Patients',u.filter(x=>x.role==='patient').length,'🧑','▲ 11%')}${stat("Today's Appointments",a.filter(x=>x.date===today()).length,'📅','Live')}${stat('Completed',a.filter(x=>x.status==='Completed').length,'✅','▲ 6%')}${stat('Cancelled',a.filter(x=>x.status==='Cancelled').length,'✖','▼ 3%')}</div><div class=card><h3>Recent appointments</h3>${apptTable(a.slice().sort((x,y)=>(y.date+y.time).localeCompare(x.date+x.time)).slice(0,8),'admin')}</div><div class=card><h3>Recent activity</h3>${db.get('notifications',[]).slice(0,5).map(x=>`<div class=nt>${esc(x.text)}<small>${x.time}</small></div>`).join('')}</div>`},
users(){return `<div class=card><div class=tools><input id=uq placeholder="Search users..." oninput=drawU() aria-label="Search users"><select id=ur onchange=drawU() aria-label="Role filter"><option value="">All roles</option><option>admin</option><option>doctor</option><option>patient</option></select><button class=btn onclick="UF()">+ Add User</button></div><div id=ut></div></div>`},
appointments(){return apptPanel(appts,'admin')},
analytics(){const a=appts(),st=cnt(a,'status'),col={Completed:'#1c6dd0',Confirmed:'#1a9d6b',Pending:'#e0a800',Cancelled:'#d33'};let acc=0;const g=Object.keys(col).map(k=>{const p=(st[k]||0)/a.length*100,s=`${col[k]} ${acc}% ${acc+p}%`;acc+=p;return s}).join(','),fb=db.get('feedback',[]),avg=fb.length?(fb.reduce((s,x)=>s+x.rating,0)/fb.length).toFixed(1):'-',m=k=>Math.round((st[k]||0)/a.length*100),mo=cnt(a.map(x=>({m:x.date.slice(0,7)})),'m');
return `<div class=grid>${stat('Total',a.length,'📅')}${stat('Completion rate',m('Completed')+'%','✅')}${stat('Cancellation rate',m('Cancelled')+'%','✖')}${stat('Avg rating',avg+' ★','⭐')}</div><div class=two><div class=card><h3>Appointment status</h3><div class=donut style="background:conic-gradient(${g})"></div><p style="text-align:center">${Object.keys(col).map(k=>`<span style="color:${col[k]}">●</span> ${k} ${st[k]||0}`).join(' &nbsp; ')}</p></div><div class=card><h3>User distribution</h3>${bars(cnt(users(),'role'))}<h3>Appointments by month</h3>${bars(mo)}</div><div class=card><h3>Department statistics</h3>${bars(cnt(a,'dept'))}</div><div class=card><h3>Doctor activity</h3>${bars(cnt(a,'doctorName'))}</div></div>`},
settings(){const s=settings();return `<form class=card onsubmit="saveSet(event)"><div class=two>${SF.map(([k,l,t])=>t==='checkbox'?`<label class=chk><input type=checkbox name=${k} ${s[k]?'checked':''}> ${l}</label>`:`<label>${l}<input name=${k} type="${t||'text'}" value="${esc(s[k])}" required></label>`).join('')}</div><button class=btn>Save settings</button></form>`},
notifications:notifView});
