const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const K=n=>'healthcare_'+n,db={get(n,d){try{const v=JSON.parse(localStorage.getItem(K(n)));return v==null?d:v}catch(e){return d}},set(n,v){localStorage.setItem(K(n),JSON.stringify(v))}};
const uid=()=>Math.random().toString(36).slice(2,9),today=()=>new Date().toISOString().slice(0,10),fd=f=>Object.fromEntries(new FormData(f));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const displayName=id=>(id.split('@')[0].replace(/[._-]+/g,' ').trim().replace(/\b\w/g,c=>c.toUpperCase()))||'User';
document.documentElement.dataset.theme=localStorage.getItem(K('theme'))||'light';
function toggleTheme(){const d=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=d;localStorage.setItem(K('theme'),d)}
const getSession=()=>{try{return JSON.parse(localStorage.getItem(K('session'))||sessionStorage.getItem(K('session')))}catch(e){return null}};
function login(userId,role,remember){const s=JSON.stringify({userId,role,name:displayName(userId)});localStorage.removeItem(K('session'));sessionStorage.removeItem(K('session'));(remember?localStorage:sessionStorage).setItem(K('session'),s);location.href=role+'.html'}
function logout(){localStorage.removeItem(K('session'));sessionStorage.removeItem(K('session'));location.href='login.html'}
function guard(role){const s=getSession();if(!s){location.replace('login.html');return null}if(s.role!==role){location.replace(s.role+'.html');return null}return s}
const pid=s=>'u_'+s.userId.toLowerCase();
const DEPTS=['Cardiology','Dermatology','Neurology','Orthopedics','Pediatrics','General Medicine'];
function seed(){if(db.get('users'))return;
const dn=['Sarah Sharma','Arjun Mehta','Priya Nair','Rahul Verma','Neha Kapoor','Vikram Rao','Ananya Iyer','Karan Malhotra','Meera Joshi','Sameer Khan'],
pn='Aarav Gupta,Diya Singh,Rohan Das,Isha Patel,Kabir Roy,Sneha Menon,Vivaan Shah,Tanya Bose,Aditya Jain,Pooja Reddy,Nikhil Rao,Riya Sen,Arnav Kulkarni,Kavya Pillai,Dev Saxena,Mira Chopra,Yash Thakur,Anika Bhatt,Harsh Vyas,Zoya Ali'.split(',');
const u=[{id:'a1',name:'System Admin',email:'admin@careplus.demo',role:'admin',phone:'+91 90000 00001',status:'Active',reg:'2025-01-05'}];
dn.forEach((n,i)=>u.push({id:'d'+(i+1),name:'Dr. '+n,email:'doctor'+(i+1)+'@careplus.demo',role:'doctor',phone:'+91 91000 000'+(10+i),status:'Active',reg:`2025-0${1+i%9}-${10+i}`,spec:DEPTS[i%6],exp:5+i*2,rating:+(4+((i*7)%10)/10).toFixed(1)}));
pn.forEach((n,i)=>u.push({id:'p'+(i+1),name:n,email:n.split(' ')[0].toLowerCase()+'@demo.mail',role:'patient',phone:'+91 98000 000'+(10+i),status:i%9==8?'Inactive':'Active',reg:`2025-0${1+i%9}-${10+i%18}`}));
db.set('users',u);
const sl=['09:00','09:30','10:00','10:30','11:00','11:30','14:00','14:30','15:00','15:30'],rs=['Routine checkup','Follow-up visit','Chest discomfort','Skin rash','Headaches','Knee pain','Fever and cold'],ap=[];
for(let i=0;i<30;i++){const p=u.find(x=>x.id==='p'+(i%20+1)),d=u.find(x=>x.id==='d'+(i%10+1)),off=i-12;
ap.push({id:'ap'+(100+i),patientId:p.id,patientName:p.name,doctorId:d.id,doctorName:d.name,dept:d.spec,date:new Date(Date.now()+off*864e5).toISOString().slice(0,10),time:sl[i%10],type:i%3?'In-person':'Video consultation',reason:rs[i%7],notes:'',diagnosis:off<0?rs[i%7]+' - reviewed':'',rx:off<0?'Vitamin D3 1000IU daily':'',status:off<0?(i%6?'Completed':'Cancelled'):(i%3?'Confirmed':'Pending')})}
db.set('appointments',ap);
db.set('feedback',ap.filter(a=>a.status==='Completed').slice(0,10).map((a,i)=>({id:'f'+i,apptId:a.id,doctorId:a.doctorId,patientName:a.patientName,rating:3+i%3,comment:['Very attentive doctor.','Clear explanation, short wait.','Great experience overall.'][i%3],date:a.date})));
db.set('notifications',[{id:'n1',role:'admin',text:'New patient registered: Zoya Ali',time:new Date().toLocaleString(),read:false},{id:'n2',role:'doctor',text:'New patient assigned to your list',time:new Date().toLocaleString(),read:false}]);
db.set('settings',{clinic:'CarePlus Clinic',email:'contact@careplus.demo',phone:'+91 11 5555 0100',address:'12 Wellness Road, Demo City',tz:'Asia/Kolkata',duration:30,window:60,maxDaily:40,cancelHrs:12,timeout:30,pwPolicy:'Minimum 8 characters',n_email:1,n_rem:1,n_sys:1,n_pat:1,loginNote:0});
db.set('schedules',[]);db.set('records',{})}
seed();
const appts=()=>db.get('appointments',[]),users=()=>db.get('users',[]),settings=()=>db.get('settings',{});
function recFor(id){const r=db.get('records',{})[id]||{},n=[...id].reduce((a,c)=>a+c.charCodeAt(0),0);return{age:20+n%50,gender:n%2?'Female':'Male',blood:['O+','A+','B+','AB+'][n%4],allergies:['None known','Penicillin','Dust'][n%3],meds:['None','Vitamin D3','Metformin 500mg'][n%3],conditions:['None','Hypertension','Seasonal asthma'][n%3],notes:'',...r}}
function notify(role,text,to){const n=db.get('notifications',[]);n.unshift({id:uid(),role,to,text,time:new Date().toLocaleString(),read:false});db.set('notifications',n)}
const myN=()=>{const s=getSession();return db.get('notifications',[]).filter(n=>n.role===s.role&&(!n.to||n.to===pid(s)))};
function readOne(id){const n=db.get('notifications',[]);n.find(x=>x.id===id).read=true;db.set('notifications',n);redraw()}
function readAll(){const ids=myN().map(x=>x.id),n=db.get('notifications',[]);n.forEach(x=>{if(ids.includes(x.id))x.read=true});db.set('notifications',n);toast('All notifications marked as read.');redraw()}
function toast(m,t='success'){let c=$('#toasts');if(!c){c=document.createElement('div');c.id='toasts';document.body.append(c)}const e=document.createElement('div');e.className='toast '+t;e.textContent=m;c.append(e);setTimeout(()=>e.remove(),3200)}
function modal(title,body,ok,label='Save'){const o=document.createElement('div');o.className='ov';o.innerHTML=`<form class=md role=dialog aria-label="${esc(title)}"><h3>${esc(title)}</h3><div>${body}</div><div class=acts><button type=button class="btn ghost" data-x>Close</button>${ok?`<button class=btn>${label}</button>`:''}</div></form>`;document.body.append(o);const f=$('form',o),close=()=>o.remove();$('[data-x]',o).onclick=close;o.onclick=e=>{if(e.target===o)close()};f.onsubmit=e=>{e.preventDefault();if(ok&&ok(f)!==false)close()};const i=$('input,select,textarea',o);i&&i.focus()}
const confirmBox=(msg,fn)=>modal('Please confirm',`<p>${msg}</p>`,()=>{fn()},'Yes, continue');
const badge=s=>`<span class="b ${String(s).toLowerCase()}">${esc(s)}</span>`;
const empty=(i,t,x)=>`<div class=empty><span>${i}</span><h3>${t}</h3><p>${x||''}</p></div>`;
const stat=(l,v,i,t)=>`<div class="card st"><span class=ic2>${i}</span><div><small>${l}</small><b>${v}</b>${t?`<em>${t}</em>`:''}</div></div>`;
const bars=o=>{const m=Math.max(1,...Object.values(o));return Object.entries(o).map(([k,v])=>`<div class=bar><span>${esc(k)}</span><div><i style="width:${v/m*100}%"></i></div><b>${v}</b></div>`).join('')};
const notifView=()=>{const l=myN();return `<div class=card><div class=row><h3>Notifications</h3><button class="btn ghost" onclick=readAll()>Mark all as read</button></div>${l.length?l.map(n=>`<div class="nt ${n.read?'':'un'}" onclick="readOne('${n.id}')">${esc(n.text)}<small>${n.time}</small></div>`).join(''):empty('🔔','No notifications','You are all caught up.')}</div>`};
const SL=[];for(let h=9;h<17;h++)['00','30'].forEach(m=>SL.push((h<10?'0':'')+h+':'+m));
function slotsFor(did,date){const sc=db.get('schedules',[]).filter(x=>x.doctorId===did&&x.date===date),bl=sc.filter(x=>x.type==='Blocked'),av=sc.filter(x=>x.type==='Available'),ap=appts().filter(a=>a.doctorId===did&&a.date===date&&a.status!=='Cancelled');
return SL.map(t=>{const a=ap.find(x=>x.time===t);const blocked=bl.some(x=>t>=x.start&&t<x.end)||(av.length&&!av.some(x=>t>=x.start&&t<x.end));return{t,s:a?(a.status==='Completed'?'Completed':'Booked'):blocked?'Blocked':'Available'}})}
function setStatus(id,st,extra){const a=appts(),x=a.find(y=>y.id===id);Object.assign(x,{status:st},extra);db.set('appointments',a);const s=getSession();
if(s.role==='patient')notify('doctor',`${x.patientName} set an appointment on ${x.date} to ${st}.`);else notify('patient',`Your ${x.dept} appointment on ${x.date} is now ${st}.`,x.patientId);
toast(`Appointment ${st.toLowerCase()}.`,st==='Cancelled'?'warning':'success');redraw()}
function resched(id){const x=appts().find(a=>a.id===id);modal('Reschedule appointment',`<label>New date<input type=date name=date min="${today()}" value="${x.date}" required></label><label>New time<input type=time name=time value="${x.time}" required></label>`,f=>{const v=fd(f);if(v.date<today()){toast('Choose a future date.','error');return false}const a=appts(),y=a.find(z=>z.id===id);y.date=v.date;y.time=v.time;db.set('appointments',a);setStatus(id,'Pending',{})},'Reschedule')}
function details(id){const x=appts().find(a=>a.id===id);modal('Appointment details',`<p><b>Patient:</b> ${esc(x.patientName)}<br><b>Doctor:</b> ${esc(x.doctorName)}<br><b>Date:</b> ${x.date} ${x.time}<br><b>Department:</b> ${x.dept}<br><b>Type:</b> ${x.type}<br><b>Reason:</b> ${esc(x.reason)}<br><b>Status:</b> ${badge(x.status)}<br><b>Notes:</b> ${esc(x.notes)||'-'}<br><b>Diagnosis:</b> ${esc(x.diagnosis)||'-'}<br><b>Prescription:</b> ${esc(x.rx)||'-'}</p>`)}
function completeAppt(id){modal('Complete consultation','<label>Diagnosis<input name=diagnosis required></label><label>Prescription<input name=rx></label><label>Consultation notes<textarea name=notes rows=3></textarea></label>',f=>setStatus(id,'Completed',fd(f)),'Mark completed')}
function feedbackForm(id){const x=appts().find(a=>a.id===id);modal('Rate your visit','<label>Rating<select name=rating><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><label>Comment<textarea name=comment rows=3 required></textarea></label>',f=>{const v=fd(f),l=db.get('feedback',[]);l.push({id:uid(),apptId:id,doctorId:x.doctorId,patientName:x.patientName,rating:+v.rating,comment:v.comment,date:today()});db.set('feedback',l);notify('doctor',`New ${v.rating}★ feedback from ${x.patientName}.`);toast('Thank you for your feedback.');redraw()},'Submit')}
const ab=(l,f)=>`<button class=sm onclick="${f}">${l}</button>`;
function apptTable(l,role){if(!l.length)return empty('📅','No appointments found','Try changing the filters.');
return `<div class=tw><table><thead><tr><th>Patient</th><th>Doctor</th><th>Date</th><th>Time</th><th>Dept</th><th>Status</th><th>Actions</th></tr></thead><tbody>${l.map(a=>{const o=a.status==='Pending'||a.status==='Confirmed';let b=ab('Details',`details('${a.id}')`);
if(role!=='patient'&&a.status==='Pending')b+=ab('Confirm',`setStatus('${a.id}','Confirmed')`);
if(role==='doctor'&&a.status==='Confirmed')b+=ab('Complete',`completeAppt('${a.id}')`);
if(o)b+=ab('Reschedule',`resched('${a.id}')`)+ab(role==='doctor'&&a.status==='Pending'?'Reject':'Cancel',`confirmBox('This appointment will be cancelled.',()=>setStatus('${a.id}','Cancelled'))`);
if(role==='patient'&&a.status==='Completed'&&!db.get('feedback',[]).some(f=>f.apptId===a.id))b+=ab('Feedback',`feedbackForm('${a.id}')`);
return `<tr><td>${esc(a.patientName)}</td><td>${esc(a.doctorName)}</td><td>${a.date}</td><td>${a.time}</td><td>${a.dept}</td><td>${badge(a.status)}</td><td>${b}</td></tr>`}).join('')}</tbody></table></div>`}
let PL;
function apptPanel(getList,role){PL={getList,role};return `<div class=card><div class=tools><input id=q placeholder="Search appointments..." oninput=drawT() aria-label=Search><select id=fs onchange=drawT() aria-label="Status filter"><option value="">All statuses</option>${['Pending','Confirmed','Completed','Cancelled'].map(s=>`<option>${s}</option>`).join('')}</select>${role==='admin'?`<select id=fdc onchange=drawT() aria-label="Doctor filter"><option value="">All doctors</option>${users().filter(u=>u.role==='doctor').map(u=>`<option>${esc(u.name)}</option>`).join('')}</select>`:''}<input type=date id=fdt onchange=drawT() aria-label=Date><select id=so onchange=drawT() aria-label=Sort><option value=date>Sort: Date</option><option value=name>Sort: Patient</option><option value=status>Sort: Status</option></select></div><div id=tb></div></div>`}
function drawT(){const g=i=>($('#'+i)||{}).value||'',q=g('q').toLowerCase(),so=g('so')||'date';const l=PL.getList().filter(a=>(!q||(a.patientName+a.doctorName+a.dept+a.reason).toLowerCase().includes(q))&&(!g('fs')||a.status===g('fs'))&&(!g('fdc')||a.doctorName===g('fdc'))&&(!g('fdt')||a.date===g('fdt')));
l.sort((a,b)=>so==='date'?(b.date+b.time).localeCompare(a.date+a.time):so==='name'?a.patientName.localeCompare(b.patientName):a.status.localeCompare(b.status));$('#tb').innerHTML=apptTable(l,PL.role)}
let CUR,SECS;
function shell(role,items,secs){const s=guard(role);if(!s)return;SECS=secs;
document.body.innerHTML=`<div class=app><aside id=sb><div class=logo>✚ CarePlus</div><nav>${items.map(([k,l,i])=>`<button data-k=${k} data-l="${l}"><span>${i}</span> ${l}</button>`).join('')}</nav><button class=lo onclick=logout()>⎋ Logout</button></aside><div class=main><header><button class="ic mb" onclick="$('#sb').classList.toggle('open')" aria-label=Menu>☰</button><h2 id=ttl></h2><span class=sp></span><button class=ic onclick=toggleTheme() aria-label="Toggle dark mode">◐</button><button class=ic onclick="go('notifications')" aria-label=Notifications>🔔<i id=nb></i></button><span class=av title="${esc(s.name)}">${esc(s.name[0])}</span></header><div class=proto>Prototype Mode • Authentication simulated • Demo Prototype uses fictional healthcare data • Not for real medical use</div><main id=main></main></div></div>`;
$$('nav button').forEach(b=>b.onclick=()=>go(b.dataset.k));go(items[0][0]);return s}
function go(k){CUR=k;$$('nav button').forEach(b=>b.classList.toggle('on',b.dataset.k===k));$('#sb').classList.remove('open');$('#ttl').textContent=$(`nav [data-k="${k}"]`).dataset.l;$('#main').innerHTML='<div class=sk></div><div class=sk></div>';setTimeout(redraw,150)}
function redraw(){const m=$('#main');m.innerHTML=SECS[CUR]();m.classList.remove('fade');void m.offsetWidth;m.classList.add('fade');$('#tb')&&drawT();$('#ut')&&drawU();const n=myN().filter(x=>!x.read).length;$('#nb').textContent=n||''}
