const DV=()=>db.get('docView','d1'),mine=()=>appts().filter(a=>a.doctorId===DV());
const dsel=()=>`<label>Viewing as doctor (demo)<select onchange="db.set('docView',this.value);redraw()">${users().filter(u=>u.role==='doctor').map(u=>`<option value=${u.id} ${u.id===DV()?'selected':''}>${esc(u.name)} - ${u.spec}</option>`).join('')}</select></label>`;
let SV={mode:'day',date:today()};
function rec(id){const p=users().find(u=>u.id===id)||{name:appts().find(a=>a.patientId===id).patientName},r=recFor(id),hist=appts().filter(a=>a.patientId===id&&a.status==='Completed');
modal('Patient record: '+p.name,`<p><b>Age:</b> ${r.age} &nbsp; <b>Gender:</b> ${r.gender}</p><label>Blood group<input name=blood value="${esc(r.blood)}"></label><label>Allergies<input name=allergies value="${esc(r.allergies)}"></label><label>Current medications<input name=meds value="${esc(r.meds)}"></label><label>Existing conditions<input name=conditions value="${esc(r.conditions)}"></label><label>Doctor notes<textarea name=notes rows=3>${esc(r.notes)}</textarea></label><b>History</b>${hist.map(h=>`<p><small>${h.date} • ${esc(h.doctorName)}</small><br>${esc(h.diagnosis)} — ${esc(h.rx)}</p>`).join('')||'<p><small>No visits yet.</small></p>'}`,f=>{const l=db.get('records',{});l[id]=fd(f);db.set('records',l);notify('patient','Your medical record was updated.',id);toast('Medical record updated.');redraw()})}
function addAv(type='Available'){modal(type==='Blocked'?'Block time':'Add availability',`<label>Date<input type=date name=date min="${today()}" value="${SV.date}" required></label><label>Start<input type=time name=start value="09:00" required></label><label>End<input type=time name=end value="13:00" required></label><label>Status<select name=type><option ${type==='Available'?'selected':''}>Available</option><option ${type==='Blocked'?'selected':''}>Blocked</option></select></label>`,f=>{const v=fd(f);if(v.end<=v.start){toast('End time must be after start time.','error');return false}const l=db.get('schedules',[]);l.push({id:uid(),doctorId:DV(),...v});db.set('schedules',l);toast('Schedule updated.');redraw()})}
const rmAv=id=>{db.set('schedules',db.get('schedules',[]).filter(x=>x.id!==id));toast('Entry removed.','info');redraw()};
const setSV=(k,v)=>{SV[k]=v;redraw()};
shell('doctor',[['dashboard','Dashboard','▦'],['schedule','My Schedule','🗓'],['appointments','Appointments','📅'],['patients','Patient Records','🧑'],['feedback','Patient Feedback','⭐'],['notifications','Notifications','🔔']],{
dashboard(){const a=mine(),t=a.filter(x=>x.date===today()),up=a.filter(x=>x.date>=today()&&['Pending','Confirmed'].includes(x.status)),fb=db.get('feedback',[]).filter(f=>f.doctorId===DV());
return `<h2>Welcome back, ${esc(getSession().name)}</h2>${dsel()}<div class=grid>${stat("Today's",t.length,'📅')}${stat('Upcoming',up.length,'⏭')}${stat('Total patients',new Set(a.map(x=>x.patientId)).size,'🧑')}${stat('Completed',a.filter(x=>x.status==='Completed').length,'✅')}${stat('Pending requests',a.filter(x=>x.status==='Pending').length,'⏳')}</div><div class=two><div class=card><h3>Today's schedule</h3>${t.length?t.map(x=>`<div class=nt>${x.time} — ${esc(x.patientName)} ${badge(x.status)}</div>`).join(''):empty('☕','No appointments today')}</div><div class=card><h3>Upcoming</h3>${up.slice(0,5).map(x=>`<div class=nt>${x.date} ${x.time} — ${esc(x.patientName)} ${badge(x.status)}</div>`).join('')||empty('📅','No upcoming appointments')}<h3>Feedback</h3>${fb.length?'Average '+(fb.reduce((s,x)=>s+x.rating,0)/fb.length).toFixed(1)+' ★ from '+fb.length+' reviews':'No reviews yet'}</div></div>`},
schedule(){const sc=db.get('schedules',[]).filter(x=>x.doctorId===DV()),chip=x=>`<button class="pick ${x.s.toLowerCase()}" style="padding:.4rem;text-align:center" disabled>${x.t}<br><small>${x.s}</small></button>`;
let v;if(SV.mode==='day')v=`<div class=gridc style="grid-template-columns:repeat(auto-fill,minmax(90px,1fr))">${slotsFor(DV(),SV.date).map(chip).join('')}</div>`;else{const d0=new Date(SV.date);v='<div class=tw><table><thead><tr><th>Day</th><th>Available</th><th>Booked</th><th>Blocked</th><th>Completed</th></tr></thead><tbody>'+[0,1,2,3,4,5,6].map(i=>{const d=new Date(d0.getTime()+i*864e5).toISOString().slice(0,10),s=slotsFor(DV(),d),c=k=>s.filter(x=>x.s===k).length;return `<tr><td>${d}</td><td>${c('Available')}</td><td>${c('Booked')}</td><td>${c('Blocked')}</td><td>${c('Completed')}</td></tr>`}).join('')+'</tbody></table></div>'}
return `${dsel()}<div class=card><div class=tools><input type=date value="${SV.date}" onchange="setSV('date',this.value)" aria-label=Date><select onchange="setSV('mode',this.value)" aria-label=View><option value=day ${SV.mode==='day'?'selected':''}>Daily view</option><option value=week ${SV.mode==='week'?'selected':''}>Weekly view</option></select><button class=btn onclick="addAv()">+ Availability</button><button class="btn ghost" onclick="addAv('Blocked')">Block time</button></div>${v}</div><div class=card><h3>Your availability entries</h3>${sc.length?sc.map(x=>`<div class=nt>${x.date} ${x.start}–${x.end} ${badge(x.type)} ${ab('Remove',`rmAv('${x.id}')`)}</div>`).join(''):empty('🗓','No entries','When a date has Available entries, only those hours can be booked.')}</div>`},
appointments(){return dsel()+apptPanel(mine,'doctor')},
patients(){const m={};mine().forEach(a=>{const e=m[a.patientId]=m[a.patientId]||{n:a.patientName,c:0,l:'',d:'-'};e.c++;if(a.status==='Completed'&&a.date>=e.l){e.l=a.date;e.d=a.diagnosis}});const l=Object.entries(m);
return dsel()+`<div class=card>${l.length?`<div class=tw><table><thead><tr><th>Patient</th><th>Age</th><th>Gender</th><th>Last visit</th><th>Diagnosis</th><th>Status</th><th>Actions</th></tr></thead><tbody>${l.map(([id,p])=>{const r=recFor(id);return `<tr><td>${esc(p.n)}</td><td>${r.age}</td><td>${r.gender}</td><td>${p.l||'-'}</td><td>${esc(p.d)}</td><td>${badge('Active')}</td><td>${ab('View / Edit',`rec('${id}')`)}</td></tr>`}).join('')}</tbody></table></div>`:empty('🧑','No patients found')}</div>`},
feedback(){const f=db.get('feedback',[]).filter(x=>x.doctorId===DV()),d={5:0,4:0,3:0,2:0,1:0};f.forEach(x=>d[x.rating]++);
return dsel()+`<div class=grid>${stat('Average rating',f.length?(f.reduce((s,x)=>s+x.rating,0)/f.length).toFixed(1)+' ★':'-','⭐')}${stat('Reviews',f.length,'💬')}</div><div class=two><div class=card><h3>Distribution</h3>${bars(Object.fromEntries([5,4,3,2,1].map(k=>[k+' ★',d[k]])))}</div><div class=card><h3>Comments</h3>${f.map(x=>`<div class=nt><b>${'★'.repeat(x.rating)}</b> ${esc(x.comment)}<small>${esc(x.patientName)} • appointment ${x.apptId} • ${x.date}</small></div>`).join('')||empty('💬','No feedback yet')}</div></div>`},
notifications:notifView});
