const S=getSession();if(S&&S.role==='patient'&&!users().some(u=>u.id===pid(S))){const l=users();l.push({id:pid(S),name:S.name,email:S.userId.includes('@')?S.userId:S.userId.toLowerCase()+'@demo.mail',role:'patient',phone:'',status:'Active',reg:today()});db.set('users',l);notify('admin','New patient registered: '+S.name)}
const mine=()=>appts().filter(a=>a.patientId===pid(S)),me=()=>users().find(u=>u.id===pid(S));
let W={step:1},PT='Upcoming';const up=a=>['Pending','Confirmed'].includes(a.status);
function pickDate(){const d=$('#bd').value;if(!d||d<today()){toast('Choose a valid future date.','error');return}W.date=d;W.step=4;redraw()}
function bookIt(e){e.preventDefault();const v=fd(e.target),d=users().find(u=>u.id===W.doc);if(!slotsFor(W.doc,W.date).find(s=>s.t===W.time&&s.s==='Available')){toast('That slot was just taken.','error');return}
const a={id:'ap'+uid(),patientId:pid(S),patientName:S.name,doctorId:d.id,doctorName:d.name,dept:d.spec,date:W.date,time:W.time,type:v.type,reason:v.reason,notes:v.notes,diagnosis:'',rx:'',status:'Pending'};const l=appts();l.push(a);db.set('appointments',l);W.last=a;
notify('doctor',`New appointment request from ${S.name} on ${a.date} ${a.time}.`);notify('admin',`${S.name} booked ${d.name} on ${a.date}.`);toast('Appointment booked successfully.');toast('Appointment is pending confirmation.','info');W.step=6;redraw()}
function ics(){const a=W.last,s=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nDTSTART:${a.date.replace(/-/g,'')}T${a.time.replace(':','')}00\r\nSUMMARY:${a.dept} with ${a.doctorName}\r\nEND:VEVENT\r\nEND:VCALENDAR`,l=document.createElement('a');l.href=URL.createObjectURL(new Blob([s],{type:'text/calendar'}));l.download='appointment.ics';l.click()}
function bookView(){const docs=users().filter(u=>u.role==='doctor'&&u.status==='Active'),mx=new Date(Date.now()+(settings().window||60)*864e5).toISOString().slice(0,10),back=W.step>1&&W.step<6?`<p><button class="btn ghost" onclick="W.step--;redraw()">← Back</button></p>`:'';
let h=`<div class=card><div class=steps>${['Specialty','Doctor','Date','Time','Details','Done'].map((s,i)=>`<span class="${i+1<=W.step?'on':''}">${i+1}. ${s}</span>`).join('')}</div>`;
if(W.step==1)h+=`<div class=gridc>${DEPTS.map(d=>`<button class=pick onclick="W.dept='${d}';W.step=2;redraw()">${d}</button>`).join('')}</div>`;
if(W.step==2)h+=`<div class=gridc>${docs.filter(d=>d.spec===W.dept).map(d=>`<button class=pick onclick="W.doc='${d.id}';W.step=3;redraw()"><b>${esc(d.name)}</b><br>${d.spec}<br><small>${d.exp} yrs • ★ ${d.rating}</small><br><span class="b available">Available</span></button>`).join('')||empty('🩺','No doctors available')}</div>`;
if(W.step==3)h+=`<label>Choose a date<input type=date id=bd min="${today()}" max="${mx}" value="${W.date||''}"></label><button class=btn onclick=pickDate()>Next</button>`;
if(W.step==4)h+=`<div class=gridc style="grid-template-columns:repeat(auto-fill,minmax(90px,1fr))">${slotsFor(W.doc,W.date).map(x=>`<button class="pick ${x.s.toLowerCase()}" style="text-align:center" ${x.s!=='Available'?'disabled':''} onclick="W.time='${x.t}';W.step=5;redraw()">${x.t}</button>`).join('')}</div>`;
if(W.step==5)h+=`<form onsubmit="bookIt(event)"><label>Reason for visit<input name=reason required minlength=3></label><label>Appointment type<select name=type><option>In-person</option><option>Video consultation</option></select></label><label>Additional notes<textarea name=notes rows=2></textarea></label><button class=btn>Confirm booking</button></form>`;
if(W.step==6){const a=W.last;h+=`<div class=empty><span>✅</span><h2>Appointment Booked</h2><p><b>${esc(a.doctorName)}</b><br>${a.dept}<br>${a.date} • ${a.time}<br>${badge(a.status)} awaiting doctor confirmation</p><button class=btn onclick=ics()>Add to Calendar</button> <button class="btn ghost" onclick="PT='Upcoming';go('appointments')">View Appointment</button> <button class="btn ghost" onclick="W={step:1};redraw()">Book Another</button></div>`}
return h+back+'</div>'}
const bookGo=()=>{W={step:1};go('book')};
shell('patient',[['dashboard','Dashboard','▦'],['book','Book Appointment','➕'],['appointments','My Appointments','📅'],['history','Medical History','📋'],['profile','Profile','👤'],['notifications','Notifications','🔔']],{
dashboard(){const a=mine(),n=a.filter(x=>up(x)&&x.date>=today()).sort((x,y)=>(x.date+x.time).localeCompare(y.date+y.time))[0],c=a.filter(x=>x.status==='Completed');
return `<h2>Welcome back, ${esc(S.name)}</h2><div class=card><h3>Next appointment</h3>${n?`<p><b>${esc(n.doctorName)}</b> • ${n.dept}<br>${n.date} at ${n.time} • ${n.type} ${badge(n.status)}</p>`:empty('📅','No upcoming appointments','Book a visit with one of our doctors.')}</div><div class=grid>${stat('Upcoming',a.filter(up).length,'📅')}${stat('Completed visits',c.length,'✅')}${stat('Medical records',c.length,'📋')}${stat('Prescriptions',c.filter(x=>x.rx).length,'💊')}</div><div class=card><h3>Quick actions</h3><button class=btn onclick=bookGo()>Book Appointment</button> <button class="btn ghost" onclick="go('history')">Medical History</button> <button class="btn ghost" onclick="go('profile')">Manage Profile</button> <button class="btn ghost" onclick="go('appointments')">View Appointments</button></div>`},
book:bookView,
appointments(){const a=mine(),f={Upcoming:a.filter(up),Past:a.filter(x=>x.status==='Completed'),Cancelled:a.filter(x=>x.status==='Cancelled')};
return `<div class=card><div class=tools>${Object.keys(f).map(k=>`<button class="btn ${k===PT?'':'ghost'}" onclick="PT='${k}';redraw()">${k} (${f[k].length})</button>`).join('')}</div>${f[PT].length?apptTable(f[PT].sort((x,y)=>y.date.localeCompare(x.date)),'patient'):empty('📅','No '+PT.toLowerCase()+' appointments','Your appointments will appear here.')}</div>`},
history(){const r=recFor(pid(S)),c=mine().filter(x=>x.status==='Completed').sort((x,y)=>y.date.localeCompare(x.date));
return `<div class=card><h3>Health summary</h3><div class=grid><div><small>Blood group</small><br><b>${r.blood}</b></div><div><small>Allergies</small><br><b>${esc(r.allergies)}</b></div><div><small>Conditions</small><br><b>${esc(r.conditions)}</b></div><div><small>Medications</small><br><b>${esc(r.meds)}</b></div></div></div><div class=two><div class=card><h3>Visit history</h3>${c.length?`<div class=tl>${c.map(x=>`<div><b>${x.date}</b> • ${esc(x.doctorName)}<br>${esc(x.diagnosis)}<br><small>${esc(x.notes)}</small></div>`).join('')}</div>`:empty('📋','No medical records found','Records appear after completed visits.')}</div><div class=card><h3>Prescriptions</h3>${c.filter(x=>x.rx).map(x=>`<div class=nt>💊 ${esc(x.rx)}<small>${x.date} • ${esc(x.doctorName)}</small></div>`).join('')||empty('💊','No prescriptions')}<h3>Documents</h3>${['Lab report (demo)','Discharge summary (demo)','Vaccination card (demo)'].map(d=>`<div class=nt>📄 ${d}</div>`).join('')}</div></div>`},
profile(){const u=me();return `<form class=card onsubmit="saveP(event)"><div class=row><span class=av style="width:64px;height:64px;font-size:1.6rem">${esc(u.name[0])}</span><small>Avatar is generated from your name</small></div><div class=two><label>Full name<input name=name value="${esc(u.name)}" required></label><label>Email<input type=email name=email value="${esc(u.email)}" required></label><label>Phone<input name=phone value="${esc(u.phone)}" pattern="[0-9+ ()\\-]{7,}" title="Valid phone number" required></label><label>Date of birth<input type=date name=dob value="${u.dob||''}" max="${today()}"></label><label>Gender<select name=gender>${['','Female','Male','Other'].map(g=>`<option ${u.gender===g?'selected':''}>${g}</option>`).join('')}</select></label><label>Address<input name=address value="${esc(u.address)}"></label><label>Emergency contact<input name=emergency value="${esc(u.emergency)}"></label><label>Change password<input type=password name=pw minlength=4 placeholder="(simulated, not stored)"></label></div><button class=btn>Save changes</button></form>`},
notifications:notifView});
function saveP(e){e.preventDefault();const v=fd(e.target);delete v.pw;const l=users();Object.assign(l.find(u=>u.id===pid(S)),v);db.set('users',l);S.name=v.name;notify('admin',`${v.name} updated their profile.`);toast('Profile updated successfully.')}
